'use client';
import Link from 'next/link'; import { useEffect, useState, useTransition } from 'react'; import { Cable, RefreshCw } from 'lucide-react';
import { getIntegrationHealth, refreshIntegrationHealth } from './actions';
type Row = { id: string; provider: string; status: string; environment: string; config: unknown; lastCheckedAt: Date | null };
export default function IntegrationsPage() { const [rows,setRows]=useState<Row[]>([]); const [error,setError]=useState(''); const [pending,startTransition]=useTransition();
  const load=async()=>{const r=await getIntegrationHealth(); if(r.success)setRows((r.data||[]) as Row[]);else setError(r.error||'Load failed.');}; useEffect(()=>{void load();},[]);
  const refresh=()=>startTransition(async()=>{const r=await refreshIntegrationHealth();if(!r.success)setError(r.error||'Check failed.');await load();});
  return <main className="min-h-screen bg-stone-50 p-6"><div className="mx-auto max-w-5xl"><Link href="/dashboard/ai-maestro" className="font-bold text-emerald-700">← Maestro</Link><div className="mt-3 flex items-center justify-between"><div><h1 className="text-3xl font-black">Integration Control</h1><p className="text-stone-600">Реална конфигурация — никога симулиран connected статус.</p></div><button disabled={pending} onClick={refresh} className="flex gap-2 rounded-xl bg-black px-4 py-3 font-bold text-white"><RefreshCw size={18}/>Провери</button></div>{error&&<p className="mt-4 rounded-xl bg-rose-100 p-4 text-rose-800">{error}</p>}<div className="mt-6 grid gap-4">{rows.map(row=>{const config=(row.config&&typeof row.config==='object'?row.config:{}) as Record<string,unknown>;return <article key={row.id} className="rounded-3xl border bg-white p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><Cable/><h2 className="text-xl font-black capitalize">{row.provider}</h2></div><span className={`rounded-full px-3 py-1 text-xs font-black ${row.status==='connected'?'bg-emerald-100 text-emerald-800':row.status==='error'?'bg-rose-100 text-rose-800':'bg-amber-100 text-amber-800'}`}>{row.status}</span></div><p className="mt-3 text-sm text-stone-600">{String(config.message||'Няма извършена проверка.')}</p><p className="mt-2 text-xs text-stone-400">{row.environment} · {row.lastCheckedAt?new Date(row.lastCheckedAt).toLocaleString():'never'}</p></article>})}{!rows.length&&<p className="rounded-3xl border border-dashed bg-white p-10 text-center font-bold">Натиснете „Провери“, за да валидирате конфигурацията.</p>}</div></div></main>;
}
