'use client';
import Link from 'next/link';
import { useEffect, useState, useTransition } from 'react';
import { Cable, RefreshCw } from 'lucide-react';
import { getIntegrationHealth, getIntegrationJobs, refreshIntegrationHealth, retryIntegrationJob, syncBankTransactions } from './actions';
type Row = { id: string; provider: string; status: string; environment: string; config: unknown; lastCheckedAt: Date | null };
type Job = { id: string; jobType: string; status: string; attempts: number; maxAttempts: number; lastError: string | null; createdAt: Date };
export default function IntegrationsPage() {
  const [rows,setRows]=useState<Row[]>([]); const [jobs,setJobs]=useState<Job[]>([]); const [error,setError]=useState(''); const [pending,startTransition]=useTransition();
  const load=async()=>{const [health,queue]=await Promise.all([getIntegrationHealth(),getIntegrationJobs()]); if(health.success)setRows((health.data||[]) as Row[]);else setError(health.error||'Load failed.'); if(queue.success)setJobs((queue.data||[]) as Job[]);};
  useEffect(()=>{void load();},[]);
  const refresh=()=>startTransition(async()=>{const result=await refreshIntegrationHealth();if(!result.success)setError(result.error||'Check failed.');await load();});
  const retry=(id:string)=>startTransition(async()=>{const result=await retryIntegrationJob(id);if(!result.success)setError(result.error||'Retry failed.');await load();});
  const syncBank=()=>startTransition(async()=>{const result=await syncBankTransactions();if(!result.success)setError(result.error||'Bank sync failed.');else setError(`Bank sync: ${result.data?.imported||0} imported, ${result.data?.skipped||0} skipped.`);await load();});
  return <main className="min-h-screen bg-stone-50 p-6"><div className="mx-auto max-w-5xl"><Link href="/dashboard/ai-maestro" className="font-bold text-emerald-700">← Maestro</Link><div className="mt-3 flex items-center justify-between"><div><h1 className="text-3xl font-black">Integration Control</h1><p className="text-stone-600">Реална конфигурация и възстановима опашка — никога симулиран connected статус.</p></div><button disabled={pending} onClick={refresh} className="flex gap-2 rounded-xl bg-black px-4 py-3 font-bold text-white"><RefreshCw size={18}/>Провери</button></div>{error&&<p className="mt-4 rounded-xl bg-rose-100 p-4 text-rose-800">{error}</p>}
  <div className="mt-6 grid gap-4">{rows.map(row=>{const config=(row.config&&typeof row.config==='object'?row.config:{}) as Record<string,unknown>;return <article key={row.id} className="rounded-3xl border bg-white p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><Cable/><h2 className="text-xl font-black capitalize">{row.provider}</h2></div><span className={`rounded-full px-3 py-1 text-xs font-black ${row.status==='connected'?'bg-emerald-100 text-emerald-800':row.status==='error'?'bg-rose-100 text-rose-800':'bg-amber-100 text-amber-800'}`}>{row.status}</span></div><p className="mt-3 text-sm text-stone-600">{String(config.message||'Няма извършена проверка.')}</p><div className="mt-2 flex items-center justify-between"><p className="text-xs text-stone-400">{row.environment} · {row.lastCheckedAt?new Date(row.lastCheckedAt).toLocaleString():'never'}</p>{row.provider==='banking'&&row.status==='connected'&&<button disabled={pending} onClick={syncBank} className="rounded-lg border px-3 py-1 text-xs font-bold">Read-only sync</button>}</div></article>})}</div>
  <section className="mt-8 rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">Integration jobs</h2><p className="mt-1 text-sm text-stone-500">Email и ZATCA задачи се появяват тук само след човешко одобрение.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Тип</th><th className="p-3">Статус</th><th className="p-3">Опити</th><th className="p-3">Грешка</th><th className="p-3"></th></tr></thead><tbody>{jobs.map(job=><tr key={job.id} className="border-b last:border-0"><td className="p-3 font-bold">{job.jobType}</td><td className="p-3">{job.status}</td><td className="p-3">{job.attempts}/{job.maxAttempts}</td><td className="max-w-sm truncate p-3 text-rose-700">{job.lastError||'—'}</td><td className="p-3">{job.status==='dead_letter'&&<button disabled={pending} onClick={()=>retry(job.id)} className="rounded-lg border px-3 py-1 font-bold">Retry</button>}</td></tr>)}</tbody></table></div></section>
  </div></main>;
}
