'use client';
import { useEffect, useState, useTransition } from 'react';
import { Archive, FileText, Loader2, Search, ShieldCheck, Upload } from 'lucide-react';
import { archiveKnowledgeDocument, getKnowledgeControlData } from './actions';
type Source = { id: string; fileName: string; title: string; version: number; status: string; visibility: string; allowedRoles: unknown; pageCount: number | null; createdAt: Date };
type Data = { sources: Source[]; metrics: { activeDocuments: number; retrievals: number; noResultRate: number; averageLatencyMs: number } };
export default function DocumentsPage() {
  const [file,setFile]=useState<File|null>(null); const [visibility,setVisibility]=useState('company'); const [roles,setRoles]=useState(['admin','finance','manager']);
  const [data,setData]=useState<Data|null>(null); const [message,setMessage]=useState(''); const [pending,startTransition]=useTransition();
  const load=async()=>{const result=await getKnowledgeControlData();if(result.success&&result.data)setData(result.data as Data);else setMessage(result.error||'Load failed.');}; useEffect(()=>{void load();},[]);
  const upload=()=>startTransition(async()=>{if(!file)return;setMessage('Обработване, chunking и embeddings…');const body=new FormData();body.append('file',file);body.append('visibility',visibility);body.append('allowedRoles',roles.join(','));const response=await fetch('/api/documents/upload',{method:'POST',body});const result=await response.json();setMessage(response.ok?`Готово: v${result.version}, ${result.pages} страници, ${result.chunksCount} chunks.`:result.error||'Upload failed.');if(response.ok){setFile(null);await load();}});
  const archive=(id:string)=>startTransition(async()=>{const result=await archiveKnowledgeDocument(id);if(!result.success)setMessage(result.error||'Archive failed.');await load();});
  const toggleRole=(role:string)=>setRoles(current=>current.includes(role)?current.filter(item=>item!==role):[...current,role]);
  return <main className="mx-auto max-w-7xl space-y-6 p-6"><div><h1 className="text-3xl font-black">Enterprise Knowledge Engine</h1><p className="mt-1 text-stone-600">Версии, ACL, hybrid search, точни citations и retrieval telemetry.</p></div>
  <section className="grid gap-4 sm:grid-cols-4">{[['Активни документи',data?.metrics.activeDocuments||0,FileText],['Retrievals',data?.metrics.retrievals||0,Search],['Без резултат',`${data?.metrics.noResultRate||0}%`,ShieldCheck],['Средна латентност',`${data?.metrics.averageLatencyMs||0} ms`,Loader2]].map(([label,value,Icon])=>{const I=Icon as typeof FileText;return <div key={String(label)} className="rounded-3xl border bg-white p-5"><I className="text-emerald-600"/><p className="mt-2 text-xs font-bold text-stone-500">{String(label)}</p><p className="text-2xl font-black">{String(value)}</p></div>})}</section>
  <section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Качи PDF версия</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><input type="file" accept="application/pdf" onChange={event=>setFile(event.target.files?.[0]||null)} className="rounded-xl border p-3"/><select value={visibility} onChange={event=>setVisibility(event.target.value)} className="rounded-xl border p-3"><option value="company">Цялата компания</option><option value="restricted">Ограничен достъп</option></select><button disabled={!file||pending} onClick={upload} className="flex items-center justify-center gap-2 rounded-xl bg-black p-3 font-bold text-white disabled:opacity-40"><Upload size={18}/>Ingest</button></div>{visibility==='restricted'&&<div className="mt-3 flex gap-3">{['admin','finance','manager','member'].map(role=><label key={role} className="flex gap-1 text-sm"><input type="checkbox" checked={roles.includes(role)} onChange={()=>toggleRole(role)}/>{role}</label>)}</div>}{message&&<p className="mt-4 rounded-xl bg-stone-100 p-3 text-sm font-bold">{message}</p>}</section>
  <section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Document registry</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Документ</th><th className="p-3">Версия</th><th className="p-3">Страници</th><th className="p-3">Достъп</th><th className="p-3">Статус</th><th></th></tr></thead><tbody>{data?.sources.map(source=><tr key={source.id} className="border-b last:border-0"><td className="p-3 font-bold">{source.title}</td><td className="p-3">v{source.version}</td><td className="p-3">{source.pageCount||'—'}</td><td className="p-3">{source.visibility}</td><td className="p-3">{source.status}</td><td className="p-3">{source.status==='active'&&<button disabled={pending} onClick={()=>archive(source.id)} className="rounded-lg border p-2 text-rose-700"><Archive size={15}/></button>}</td></tr>)}</tbody></table></div></section></main>;
}
